In [1]:
import pandas as pd
import numpy as np

In [2]:
points = pd.read_csv("points.csv",index_col=0)

In [3]:
points.T

0,GAS,GIO,NOR,RUS,MAZ,ALO,RAI,LAT,SAI,STR,...,VET,MSC,KUB,VER,LEC,OCO,TSU,PER,BOT,HAM
1,0.0,0.0,12.0,0.0,0.0,0.0,0.0,0.0,4.0,1.0,...,0.0,0.0,NaN,18.0,8.0,0.0,2.0,10.0,16.0,25.0
2,6.0,0.0,15.0,0.0,0.0,1.0,0.0,0.0,10.0,4.0,...,0.0,0.0,NaN,25.0,12.0,2.0,0.0,0.0,0.0,19.0
3,1.0,0.0,10.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,NaN,18.0,8.0,6.0,0.0,12.0,16.0,25.0
4,1.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,...,0.0,0.0,NaN,19.0,12.0,2.0,0.0,10.0,15.0,25.0
5,8.0,1.0,15.0,0.0,0.0,0.0,0.0,0.0,18.0,4.0,...,10.0,0.0,NaN,25.0,0.0,2.0,0.0,12.0,0.0,7.0
6,15.0,0.0,10.0,0.0,0.0,8.0,1.0,0.0,4.0,0.0,...,18.0,0.0,NaN,0.0,12.0,0.0,6.0,25.0,0.0,0.0
7,6.0,0.0,10.0,0.0,0.0,4.0,0.0,0.0,0.0,1.0,...,2.0,0.0,NaN,26.0,0.0,0.0,0.0,15.0,12.0,18.0
8,0.0,0.0,10.0,0.0,0.0,2.0,0.0,0.0,8.0,4.0,...,0.0,0.0,NaN,25.0,6.0,0.0,1.0,12.0,15.0,19.0
9,2.0,0.0,15.0,0.0,0.0,1.0,0.0,0.0,10.0,0.0,...,0.0,0.0,NaN,26.0,4.0,0.0,0.0,8.0,18.0,12.0
10,0.0,0.0,12.0,0.0,0.0,6.0,0.0,0.0,8.0,4.0,...,0.0,0.0,NaN,0.0,18.0,2.0,1.0,0.0,15.0,25.0
11,11.0,0.0,0.0,4.0,0.0,12.0,1.0,6.0,15.0,0.0,...,0.0,0.0,NaN,2.0,0.0,25.0,8.0,0.0,0.0,18.0
12,4.0,0.0,0.0,9.0,0.0,0.0,0.0,1.0,0.5,0.0,...,5.0,0.0,NaN,12.5,2.0,3.0,0.0,0.0,0.0,7.5
13,12.0,0.0,1.0,0.0,0.0,8.0,NaN,0.0,6.0,0.0,...,0.0,0.0,0.0,25.0,10.0,2.0,0.0,4.0,15.0,19.0
14,0.0,0.0,18.0,2.0,0.0,4.0,NaN,0.0,8.0,6.0,...,0.0,0.0,0.0,0.0,12.0,1.0,0.0,10.0,15.0,0.0
15,0.0,0.0,7.0,1.0,0.0,8.0,4.0,0.0,15.0,0.0,...,0.0,0.0,NaN,18.0,0.0,0.0,0.0,2.0,10.0,25.0
16,8.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,4.0,2.0,...,0.0,0.0,NaN,18.0,12.0,1.0,0.0,15.0,26.0,10.0
17,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,...,1.0,0.0,NaN,25.0,12.0,0.0,2.0,15.0,8.0,19.0
18,12.0,0.0,1.0,0.0,0.0,2.0,4.0,0.0,8.0,0.0,...,6.0,0.0,NaN,25.0,10.0,0.0,0.0,15.0,0.0,18.0
19,6.0,0.0,1.0,0.0,0.0,2.0,0.0,0.0,8.0,0.0,...,0.0,0.0,NaN,18.0,10.0,4.0,0.0,13.0,15.0,25.0
20,0.0,0.0,2.0,0.0,0.0,15.0,0.0,0.0,6.0,8.0,...,1.0,0.0,NaN,19.0,4.0,10.0,0.0,12.0,0.0,25.0
21,8.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,...,0.0,0.0,NaN,18.0,6.0,12.0,0.0,0.0,15.0,26.0
22,10.0,0.0,6.0,0.0,0.0,4.0,0.0,0.0,15.0,0.0,...,0.0,0.0,NaN,26.0,1.0,2.0,12.0,0.0,8.0,18.0

In [4]:
def init_dict():
    drivers = {i : 0 for i in list(points.index)}
    for key in drivers.keys():
        drivers[key] = {i : 0 for i in list(points.index)}
    return(drivers)
overall_drivers = init_dict()

for agonas in np.asarray(points.T):
#agonas = np.asarray(points.T)[0]
    drivers = init_dict()
    cnt = 0
    for driver in drivers:
        sum_loss = 0
        driver_score = agonas[cnt]
        cnt += 1
        cnt2 = 0
        for score in agonas:
            if driver_score <= score:
                drivers[driver][list(drivers.keys())[cnt2]] += 1
                sum_loss += 1
            cnt2 += 1
        if sum_loss != 0:
            for key in overall_drivers[driver]:
                overall_drivers[driver][key] += drivers[driver][key]/sum_loss

In [5]:
pd.DataFrame(overall_drivers).T

,GAS,GIO,NOR,RUS,MAZ,ALO,RAI,LAT,SAI,STR,...,VET,MSC,KUB,VER,LEC,OCO,TSU,PER,BOT,HAM
GAS,2.989683,0.350000,1.113492,0.516667,0.35,0.650000,0.300000,0.350000,1.413492,0.350000,...,1.016667,0.35,0.05,2.456349,1.113492,0.916667,0.550000,1.863492,1.530159,2.489683
GIO,1.211111,1.211111,1.100000,1.000000,1.00,1.000000,0.900000,1.000000,1.211111,1.100000,...,1.100000,1.00,0.10,1.211111,1.111111,1.211111,1.000000,1.100000,1.111111,1.211111
NOR,0.985714,0.200000,4.089683,0.100000,0.10,0.653968,0.200000,0.100000,1.480159,0.211111,...,0.400000,0.10,0.00,3.139683,1.453968,0.511111,0.242857,1.703968,2.511905,2.723016
RUS,1.025000,0.900000,1.111111,1.736111,0.90,1.236111,0.950000,1.025000,1.236111,1.011111,...,0.900000,0.90,0.05,1.500000,1.011111,1.025000,1.025000,1.111111,1.111111,1.125000
MAZ,1.100000,1.100000,1.100000,1.100000,1.10,1.100000,1.000000,1.100000,1.100000,1.100000,...,1.100000,1.10,0.10,1.100000,1.100000,1.100000,1.100000,1.100000,1.100000,1.100000
ALO,1.355556,0.350000,1.470635,0.350000,0.35,2.609524,0.461111,0.350000,1.692857,0.686111,...,0.627778,0.35,0.00,1.925000,1.609524,0.936111,0.475000,1.325000,1.648413,2.317857
RAI,1.125000,0.800000,1.025000,0.900000,0.80,1.125000,1.250000,0.900000,1.250000,0.800000,...,1.025000,0.80,0.00,1.150000,1.025000,0.900000,1.000000,1.025000,0.925000,1.150000
LAT,1.253968,1.000000,1.000000,1.111111,1.00,1.142857,0.900000,1.253968,1.142857,1.000000,...,1.111111,1.00,0.10,1.111111,1.111111,1.253968,1.142857,1.000000,1.000000,1.253968
SAI,0.884524,0.100000,1.375000,0.200000,0.10,0.510714,0.100000,0.200000,4.004762,0.242857,...,0.325000,0.10,0.00,3.213095,1.995238,0.801190,0.225000,1.570238,1.770238,3.213095
STR,1.111111,0.650000,1.603968,0.650000,0.65,1.041667,0.600000,0.650000,1.503968,1.770635,...,0.875000,0.65,0.05,1.502778,1.378968,0.816667,0.750000,1.520635,1.353968,1.627778
RIC,0.561111,0.450000,1.491270,0.700000,0.45,0.672222,0.400000,0.450000,1.120635,0.450000,...,0.561111,0.45,0.05,2.246825,1.548413,0.761111,0.561111,1.491270,1.580159,2.446825
VET,1.003968,0.750000,1.261111,0.950000,0.75,0.961111,0.650000,0.750000,1.292857,0.850000,...,2.103968,0.75,0.10,1.603968,1.092857,0.850000,0.850000,1.903968,0.961111,1.403968
MSC,1.100000,1.100000,1.100000,1.100000,1.10,1.100000,1.000000,1.100000,1.100000,1.100000,...,1.100000,1.10,0.10,1.100000,1.100000,1.100000,1.100000,1.100000,1.100000,1.100000
KUB,0.100000,0.100000,0.100000,0.100000,0.10,0.100000,0.000000,0.100000,0.100000,0.100000,...,0.100000,0.10,0.10,0.100000,0.100000,0.100000,0.100000,0.100000,0.100000,0.100000
VER,0.261111,0.150000,0.150000,0.261111,0.15,0.261111,0.100000,0.261111,0.261111,0.150000,...,0.150000,0.15,0.05,14.261111,0.150000,0.261111,0.261111,0.150000,0.650000,3.761111
LEC,1.217857,0.200000,1.401190,0.325000,0.20,0.425000,0.200000,0.200000,0.692857,0.325000,...,0.575000,0.20,0.00,2.894048,3.894048,0.692857,0.300000,2.076190,2.194048,3.144048
OCO,1.212302,0.400000,1.298413,0.642857,0.40,1.033333,0.400000,0.400000,1.391667,0.933333,...,0.653968,0.40,0.00,1.916270,1.312302,3.127381,0.511111,1.401190,1.562302,2.027381
TSU,1.059524,0.750000,1.315079,0.750000,0.75,1.259524,0.650000,0.750000,1.588889,0.950000,...,0.892857,0.75,0.10,1.322222,1.315079,1.016667,1.731746,1.215079,1.172222,1.588889
PER,0.425000,0.300000,1.227778,0.300000,0.30,0.786111,0.411111,0.300000,0.952778,0.300000,...,0.300000,0.30,0.00,3.686111,0.825000,0.300000,0.300000,4.886111,2.386111,3.102778
BOT,0.516667,0.350000,0.683333,0.350000,0.35,0.350000,0.350000,0.350000,0.716667,0.350000,...,0.350000,0.35,0.00,3.966667,0.850000,0.350000,0.516667,0.766667,5.633333,3.800000
HAM,0.242857,0.100000,0.492857,0.433333,0.10,0.100000,0.050000,0.100000,0.242857,0.100000,...,0.242857,0.10,0.05,4.526190,0.300000,0.600000,0.100000,0.442857,0.550000,13.026190

In [23]:
p=np.asarray(pd.DataFrame(overall_drivers).T)
s=np.ones((21,21))
Q=0.85*p+(0.15)*(1/21)*s
from numpy import linalg as LA
w, v = LA.eig(Q)
pd.DataFrame(w)

                             0
0   1.879133e+01+0.000000e+00j
1   1.064533e+01+0.000000e+00j
2   8.033746e+00+0.000000e+00j
3   4.168748e+00+7.945062e-01j
4   4.168748e+00-7.945062e-01j
5   2.461017e+00+5.400032e-01j
6   2.461017e+00-5.400032e-01j
7   2.443886e+00+0.000000e+00j
8   1.851232e+00+4.983578e-01j
9   1.851232e+00-4.983578e-01j
10  1.840083e+00+0.000000e+00j
11  1.657965e+00+0.000000e+00j
12  9.445954e-01+0.000000e+00j
13  8.798691e-01+0.000000e+00j
14  7.406866e-01+0.000000e+00j
15  5.749411e-01+0.000000e+00j
16  3.932289e-01+0.000000e+00j
17  1.961148e-01+0.000000e+00j
18  1.005584e-01+0.000000e+00j
19  6.736690e-02+0.000000e+00j
20  1.025004e-18+0.000000e+00j

In [7]:
eig_vec = pd.DataFrame(w).join(pd.DataFrame(points.index))

In [8]:
eig_vec.columns = ['Points', 'Driver']

In [9]:
#eig_vec.sort_values(by='Points', ascending=False)

In [26]:
eig_vec.sort_values(by = ['Points'], ascending = True)

                        Points Driver
20  1.025004e-18+0.000000e+00j    HAM
19  6.736690e-02+0.000000e+00j    BOT
18  1.005584e-01+0.000000e+00j    PER
17  1.961148e-01+0.000000e+00j    TSU
16  3.932289e-01+0.000000e+00j    OCO
15  5.749411e-01+0.000000e+00j    LEC
14  7.406866e-01+0.000000e+00j    VER
13  8.798691e-01+0.000000e+00j    KUB
12  9.445954e-01+0.000000e+00j    MSC
11  1.657965e+00+0.000000e+00j    VET
10  1.840083e+00+0.000000e+00j    RIC
9   1.851232e+00-4.983578e-01j    STR
8   1.851232e+00+4.983578e-01j    SAI
7   2.443886e+00+0.000000e+00j    LAT
6   2.461017e+00-5.400032e-01j    RAI
5   2.461017e+00+5.400032e-01j    ALO
4   4.168748e+00-7.945062e-01j    MAZ
3   4.168748e+00+7.945062e-01j    RUS
2   8.033746e+00+0.000000e+00j    NOR
1   1.064533e+01+0.000000e+00j    GIO
0   1.879133e+01+0.000000e+00j    GAS